export const IMAGE_FILE_NAMES = {
  AC: 'ac.webp',
  AIRPLANE: 'airplane.webp',
  APPLE: 'apple.webp',
  ATM: 'atm.webp',
  BABY: 'baby.webp',
  BACON: 'bacon.webp',
  BALLET: 'ballet.webp',
  BALLOON: 'balloon.webp',
  BALLOON_2: 'balloon-2.webp',
  BAND: 'band.webp',
  BANANA: 'banana.webp',
  BEAR: 'bear.webp',
  BENCH: 'bench.webp',
  BIRD: 'bird.webp',
  BOOK: 'book.webp',
  BOOKS: 'books.webp',
  BOOTS: 'boots.webp',
  BOTTLE: 'bottle.webp',
  BOXES: 'boxes.webp',
  BRACELET: 'bracelet.webp',
  BROOM: 'broom.webp',
  BUS: 'bus.webp',
  BUTTERFLY: 'butterfly.webp',
  BIKE: 'bike.webp',
  CAMERA: 'camera.webp',
  CAMERA_2: 'camera-2.webp',
  CAR: 'car.webp',
  CASTLE: 'castle.webp',
  CASTLE_2: 'castle-2.webp',
  CAT: 'cat.webp',
  CHAIR: 'chair.webp',
  CHAIR_2: 'chair-2.webp',
  CHEMISTRY: 'chemistry.webp',
  CHERRY: 'cherry.webp',
  CHICKEN: 'chicken.webp',
  CHIPS: 'chips.webp',
  CHOCOLATE_BAR: 'chocolate-bar.webp',
  CHRISTMAS: 'christmas.webp',
  CLEF: 'clef.webp',
  CLOCK: 'clock.webp',
  COFFEE: 'coffee.webp',
  COFFEE_2: 'coffee-2.webp',
  COMB: 'comb.webp',
  COMB_2: 'comb-2.webp',
  COMPUTER: 'computer.webp',
  CONTACT_BOOK: 'contact-book.webp',
  CONTRACT: 'contract.webp',
  CONTROLLER: 'controller.webp',
  COURIER: 'courier.webp',
  COW: 'cow.webp',
  CRANE: 'crane.webp',
  CUBE: 'cube.webp',
  DANCE: 'dance.webp',
  DETECTIVE: 'detective.webp',
  DIARY: 'diary.webp',
  DINO: 'dino.webp',
  DINO_2: 'dino-2.webp',
  DISHES: 'dishes.webp',
  DISCO: 'disco.webp',
  THERMOMETER: 'thermometer.webp',
  DOCUMENT: 'document.webp',
  DOCTOR: 'doctor.webp',
  DOLL: 'doll.webp',
  DUCK: 'duck.webp',
  EGG: 'egg.webp',
  EMOTION: 'emotion.webp',
  FIRE: 'fire.webp',
  FISHING: 'fishing.webp',
  FLASHLIGHT: 'flashlight.webp',
  FLOWERS: 'flowers.webp',
  FOOTBALL: 'football.webp',
  FOREST: 'forest.webp',
  FRIDGE: 'fridge.webp',
  GUITAR: 'guitar.webp',
  GLASSES: 'glasses.webp',
  GLOBE: 'globe.webp',
  GUN: 'gun.webp',
  HAMBURGER: 'hamburger.webp',
  HAT: 'hat.webp',
  HEADPHONES: 'headphones.webp',
  HEART: 'heart.webp',
  HEELS: 'heels.webp',
  HOLLYWOOD: 'hollywood.webp',
  HONEY: 'honey.webp',
  HORSE: 'horse.webp',
  HURRICANE: 'hurricane.webp',
  ICE_CREAM: 'ice-cream.webp',
  ICE_CREAM_2: 'ice-cream-2.webp',
  JACKET: 'jacket.webp',
  KETTLE: 'kettle.webp',
  KEY: 'key.webp',
  KEYS: 'keys.webp',
  KING: 'king.webp',
  KNIFE: 'knife.webp',
  LAKE: 'lake.webp',
  LAMP: 'lamp.webp',
  LAPTOP: 'laptop.webp',
  LAUNDRY: 'laundry.webp',
  LEARNING: 'learning.webp',
  LIKE: 'like.webp',
  LOCK: 'lock.webp',
  LOCOMOTIVE: 'locomotive.webp',
  MAPS: 'maps.webp',
  MESSAGE: 'message.webp',
  MILK_SHAKE: 'milk-shake.webp',
  MONEY: 'money.webp',
  MONEYBOX: 'moneybox.webp',
  MOUNT: 'mount.webp',
  MUESLI: 'muesli.webp',
  MUSTARD: 'mustard.webp',
  NEWS: 'news.webp',
  NEWS_2: 'news-2.webp',
  NIGHT: 'night.webp',
  PAWN: 'pawn.webp',
  PARTY: 'party.webp',
  PEN: 'pen.webp',
  PENCIL: 'pencil.webp',
  PEOPLE: 'people.webp',
  PIG: 'pig.webp',
  PILLS: 'pills.webp',
  PING_PONG: 'ping-pong.webp',
  POINT: 'point.webp',
  POOL: 'pool.webp',
  POOP: 'poop.webp',
  PRESSURE: 'pressure.webp',
  PROTEIN_BAR: 'protein-bar.webp',
  QUEEN: 'queen.webp',
  QUESTION: 'question.webp',
  RACE: 'race.webp',
  RESTAURANT: 'restaurant.webp',
  RING: 'ring.webp',
  ROBOT_MAN: 'robot-man.webp',
  ROSE: 'rose.webp',
  RUNNING: 'running.webp',
  SALESMAN: 'salesman.webp',
  SALT: 'salt.webp',
  SAUSAGE: 'sausage.webp',
  SHOE: 'shoes.webp',
  SHORTS: 'shorts.webp',
  SHOWER: 'shower.webp',
  SKATEBOARD: 'skateboard.webp',
  SKIRT: 'skirt.webp',
  SKIRT_2: 'skirt-2.webp',
  SKUNK: 'skunk.webp',
  SNEAKERS: 'sneakers.webp',
  SNEAKERS_2: 'sneakers-2.webp',
  SOAP: 'soap.webp',
  SPEAKER: 'speaker.webp',
  SPORT: 'sport.webp',
  STAND_UP: 'stand-up.webp',
  STRONG: 'strong.webp',
  SUNGLASSES: 'sunglasses.webp',
  SWEATER: 'sweater.webp',
  SWEET: 'sweet.webp',
  TABLET: 'tablet.webp',
  TABLET_2: 'tablet-2.webp',
  TABLETS: 'tablets.webp',
  TANK: 'tank.webp',
  TANDEM: 'tandem.webp',
  TAXI: 'taxi.webp',
  TEETH: 'teeth.webp',
  THERMOS: 'thermos.webp',
  TIME: 'time.webp',
  TO_DO: 'to-do.webp',
  TOOTHBRUSH: 'toothbrush.webp',
  TRAFFIC_LIGHT: 'traffic_light.webp',
  TRAM: 'tram.webp',
  TROUSERS: 'trousers.webp',
  TUB: 'tub.webp',
  TURTLE: 'turtle.webp',
  VOLLEYBALL: 'volleyball.webp',
  WAITER: 'waiter.webp',
  WALLET: 'wallet.webp',
  WARNING: 'warning.webp',
  WATERMELON: 'watermelon.webp',
  WELCOME: 'welcome.webp',
  WHISKY: 'whisky.webp',
  WI_FI: 'wi-fi.webp',
  WINE: 'wine.webp',
  WOMAN: 'woman.webp',
  WORK_PLACE: 'work-place.webp',
  YIN_YANG: 'yin-yang.webp',
};

export const IMAGE_GERMAN_NAMES = {
  AC: 'die Klimaanlage',
  AIRPLANE: 'das Flugzeug',
  APPLE: 'der Apfel',
  ATM: 'der Geldautomat',
  BABY: 'das Baby',
  BACON: 'der Speck',
  BALLET: 'das Ballett',
  BALLOON: 'der Ballon',
  BALLOON_2: 'der Ballon',
  BAND: 'die Band',
  BANANA: 'die Banane',
  BEAR: 'der Bär',
  BENCH: 'die Bank',
  BIKE: 'das Fahrrad',
  BIRD: 'der Vogel',
  BOAT: 'das Boot',
  BOOK: 'das Buch',
  BOOKS: 'die Bücher',
  BOOTS: 'die Stiefel',
  BOTTLE: 'die Flasche',
  BOXES: 'die Kisten',
  BRACELET: 'das Armband',
  BROOM: 'der Besen',
  BULB: 'die Glühbirne',
  BUS: 'der Bus',
  BUTTERFLY: 'der Schmetterling',
  CAMERA: 'die Kamera',
  CAMERA_2: 'die Kamera',
  CAR: 'das Auto',
  CASTLE: 'das Schloss',
  CASTLE_2: 'das Schloss',
  CAT: 'die Katzen',
  CHAIR: 'der Stuhl',
  CHAIR_2: 'der Stuhl',
  CHEMISTRY: 'die Chemie',
  CHERRY: 'die Kirsche',
  CHICKEN: 'das Huhn',
  CHIPS: 'die Pommes',
  CHOCOLATE_BAR: 'die Schokolade',
  CLOCK: 'die Uhr',
  CLEF: 'der Notenschlüssel',
  COMB: 'der Kamm',
  COMB_2: 'der Kamm',
  COMPUTER: 'der Computer',
  CONTACT_BOOK: 'das Adressbuch',
  CONTROLLER: 'der Controller',
  CONTRACT: 'der Vertrag',
  COFFEE: 'der Kaffee',
  COFFEE_2: 'der Kaffee',
  COURIER: 'der Kurier',
  COW: 'die Kuh',
  CRANE: 'der Kran',
  CUBE: 'der Würfel',
  DANCE: 'der Tanz',
  DETECTIVE: 'der Detektiv',
  DIARY: 'das Tagebuch',
  THERMOMETER: 'das Thermometer',
  DINO: 'der Dino',
  DINO_2: 'der Dino',
  DISCO: 'die Disko',
  DISHES: 'das Geschirr',
  DOCUMENT: 'das Dokument',
  DOLL: 'die Puppe',
  DOCTOR: 'der Arzt',
  DRAGON: 'der Drache',
  DRESS: 'das Kleid',
  DUCK: 'die Ente',
  EGG: 'das Ei',
  EMOTION: 'die Emotion',
  FIRE: 'das Feuer',
  FISHING: 'das Angeln',
  FLASHLIGHT: 'die Taschenlampe',
  FLOWERS: 'die Blumen',
  FOOTBALL: 'der Fußball',
  FOREST: 'der Wald',
  FRIDGE: 'der Kühlschrank',
  GLASSES: 'die Brille',
  GLOBE: 'der Globus',
  GUITAR: 'die Gitarre',
  GUN: 'die Pistole',
  HAMBURGER: 'der Hamburger',
  HAT: 'der Hut',
  HEADPHONES: 'der Kopfhörer',
  HEART: 'das Herz',
  HEELS: 'die Absätze',
  HONEY: 'der Honig',
  HOLLYWOOD: 'Hollywood',
  HORSE: 'das Pferd',
  HURRICANE: 'der Wirbelsturm',
  ICE_CREAM: 'das Eis',
  ICE_CREAM_2: 'das Eis',
  JACKET: 'die Jacke',
  KETTLE: 'der Wasserkocher',
  KEY: 'der Schlüssel',
  KEYS: 'die Schlüssel',
  KING: 'der König',
  KNIFE: 'das Messer',
  LAKE: 'der See',
  LAMP: 'die Lampe',
  LAPTOP: 'der Laptop',
  LAUNDRY: 'die Wäsche',
  LEARNING: 'das Lernen',
  LIKE: 'das Gefällt mir',
  LOCK: 'das Schloss',
  LOCOMOTIVE: 'die Lokomotive',
  MAPS: 'die Karten',
  MESSAGE: 'die Nachricht',
  MILK_SHAKE: 'der Milchshake',
  MONEY: 'das Geld',
  MONEYBOX: 'die Sparbüchse',
  MOUNT: 'der Berg',
  MUESLI: 'das Müsli',
  MUSTARD: 'der Senf',
  NEWS: 'die Nachrichten',
  NEWS_2: 'die Nachrichten',
  NIGHT: 'die Nacht',
  PAWN: 'die Spielfigur',
  PARTY: 'die Party',
  PENCIL: 'der Bleistift',
  PEN: 'der Stift',
  PEOPLE: 'die Leute',
  PILLS: 'die Pillen',
  PIG: 'das Schwein',
  PING_PONG: 'das Tischtennis',
  POOL: 'der Pool',
  POOP: 'der Kot',
  PRESSURE: 'der Druck',
  PROTEIN_BAR: 'der Proteinriegel',
  QUEEN: 'die Königin',
  QUESTION: 'die Frage',
  RACE: 'das Rennen',
  RESTAURANT: 'das Restaurant',
  RING: 'der Ring',
  ROBOT_MAN: 'der Roboter-Mann',
  ROSE: 'die Rose',
  RUNNING: 'das Laufen',
  SALESMAN: 'der Verkäufer',
  SALT: 'das Salz',
  SAUSAGE: 'die Wurst',
  SHOWER: 'die Dusche',
  SHORTS: 'die Shorts',
  SHOES: 'die Schuhe',
  SKATEBOARD: 'das Skateboard',
  SKIRT: 'der Rock',
  SKIRT_2: 'der Rock',
  SKUNK: 'der Stinktier',
  SNEAKERS: 'die Turnschuhe',
  SNEAKERS_2: 'die Turnschuhe',
  SOAP: 'die Seife',
  SPEAKER: 'der Lautsprecher',
  SPORT: 'der Sport',
  STAND_UP: 'das Stand-up',
  STRONG: 'stark',
  SUNGLASSES: 'die Sonnenbrille',
  SWEATER: 'der Pullover',
  SWEET: 'die Süßigkeit',
  TABLET: 'das Tablet',
  TABLET_2: 'das Tablet',
  TABLETS: 'die Tabletten',
  TANK: 'der Panzer',
  TANDEM: 'das Tandem',
  TAXI: 'das Taxi',
  TEETH: 'die Zähne',
  THERMOS: 'der Thermos',
  TIME: 'die Zeit',
  TO_DO: 'die To-do-Liste',
  TOOTHBRUSH: 'die Zahnbürste',
  TRAFFIC_LIGHT: 'die Ampel',
  TRAM: 'die Straßenbahn',
  TROUSERS: 'die Hose',
  TUB: 'die Badewanne',
  TURTLE: 'die Schildkröte',
  VOLLEYBALL: 'der Volleyball',
  WALLET: 'die Brieftasche',
  WAITER: 'der Kellner',
  WARNING: 'die Warnung',
  WATERMELON: 'die Wassermelone',
  WELCOME: 'willkommen',
  WHISKY: 'der Whisky',
  WI_FI: 'das WLAN',
  WINE: 'der Wein',
  WOMAN: 'die Frau',
  WORK_PLACE: 'der Arbeitsplatz',
  YIN_YANG: 'das Yin und Yang',
};

export const IMAGE_NAMES_ARR = Object.keys(IMAGE_FILE_NAMES);
